### ISSUE TITLE
Memory allocation issue

### ISSUE THREAD

**Issue by yvanblanchard** [linus131/StlSlicer#2]
Hello,

I have a large input STL mesh file (binary, 325MB, with 6.5M polygons), but the system hangs and in the console it says that a bad memory allocation happened.
Did your slicer works/suitable for such large meshes ?

Thank you

**Comment by yvanblanchard** [comment]
I did another test on another STL mesh, but smaller, and I get the same error in console:
![image](https://user-images.githubusercontent.com/63931618/227294793-5728082c-005e-4eb7-a43e-f9e137fd7434.png)

The common thing between this smaller and bigger mesh file, is it's a non-connex and manifold surfacic mesh. Is it supported by your algorithm ?

![image](https://user-images.githubusercontent.com/63931618/227295523-d49ebd87-3be8-4c6e-8f3e-0e7c2b78c535.png)

Here is the STL file:
[NidaSurf.zip](https://github.com/linus131/StlSlicer/files/11054067/NidaSurf.zip)

**Comment by linus131** [comment]
Hi Yvan,
The program can slice the STL file that you included. I am attaching the screenshot of the output and a plot of the sliced segments. Since the STL mesh has open areas (not a closed surface), the slicing lines generated will not be closed. 
Much better-sliced contours can be generated by repairing the STL file. I am attaching a screenshot of repaired segments as well.


Best Regards,Sunil
    On Thursday, March 23, 2023, 01:45:25 PM EDT, Yvan Blanchard ***@***.***> wrote:  
 
 


I did another test on another STL mesh, but smaller, and I get the same error in console:


The common thing between this smaller and bigger mesh file, is it's a non-connex and manifold surfacic mesh. Is it supported by your algorithm ?



Here is the STL file:
NidaSurf.zip

**Comment by yvanblanchard** [comment]
Hi Sunil,

I can't see the attached data in your reply ?

And I'm not sure to understand why it does not work at my side.
Is it how I compiled the sources ?

I know that this input STL mesh is not closed, and that would lead to open contours, but it's not a big deal for me (the results will not be used to build a slice surface t be filled by a toolpath).

**Comment by yvanblanchard** [comment]
Thank you Sunil.
I checked at my side, by opening the STL mesh file in MeshLab then exporting to STL again (so , new STL file generated), and it works fine now.
Thank you again for your help.
